# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexusrag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nexusrag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enexusrag.proto\"z\n\x10RetrievalRequest\x12\x16\n\x0e\x63haracter_name\x18\x01 \x01(\t\x12\x10\n\x08manga_id\x18\x02 \x01(\t\x12\x12\n\nquery_text\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x05 \x01(\x05\"e\n\x0c\x41pprovedLine\x12\x10\n\x08panel_id\x18\x01 \x01(\t\x12\x19\n\x11original_japanese\x18\x02 \x01(\t\x12\x14\n\x0c\x66inal_output\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"L\n\x11RetrievalResponse\x12\x1c\n\x05lines\x18\x01 \x03(\x0b\x32\r.ApprovedLine\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x05\x32Q\n\x10RetrievalService\x12=\n\x14RetrieveSimilarLines\x12\x11.RetrievalRequest\x1a\x12.RetrievalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexusrag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVALREQUEST']._serialized_start=18
  _globals['_RETRIEVALREQUEST']._serialized_end=140
  _globals['_APPROVEDLINE']._serialized_start=142
  _globals['_APPROVEDLINE']._serialized_end=243
  _globals['_RETRIEVALRESPONSE']._serialized_start=245
  _globals['_RETRIEVALRESPONSE']._serialized_end=321
  _globals['_RETRIEVALSERVICE']._serialized_start=323
  _globals['_RETRIEVALSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
