# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nexusrag_pb2 as nexusrag__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexusrag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveSimilarLines = channel.unary_unary(
                '/RetrievalService/RetrieveSimilarLines',
                request_serializer=nexusrag__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=nexusrag__pb2.RetrievalResponse.FromString,
                _registered_method=True)


class RetrievalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RetrieveSimilarLines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveSimilarLines': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSimilarLines,
                    request_deserializer=nexusrag__pb2.RetrievalRequest.FromString,
                    response_serializer=nexusrag__pb2.RetrievalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveSimilarLines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RetrievalService/RetrieveSimilarLines',
            nexusrag__pb2.RetrievalRequest.SerializeToString,
            nexusrag__pb2.RetrievalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """Experiment 4: Ricart-Agrawala Mutual Exclusion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestCriticalSection = channel.unary_unary(
                '/MutexService/RequestCriticalSection',
                request_serializer=nexusrag__pb2.MutexRequest.SerializeToString,
                response_deserializer=nexusrag__pb2.MutexResponse.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """Experiment 4: Ricart-Agrawala Mutual Exclusion
    """

    def RequestCriticalSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestCriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCriticalSection,
                    request_deserializer=nexusrag__pb2.MutexRequest.FromString,
                    response_serializer=nexusrag__pb2.MutexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """Experiment 4: Ricart-Agrawala Mutual Exclusion
    """

    @staticmethod
    def RequestCriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MutexService/RequestCriticalSection',
            nexusrag__pb2.MutexRequest.SerializeToString,
            nexusrag__pb2.MutexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaServiceStub:
    """============================================================
    Experiment 7: Eventual Consistency via Gossip Replication
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveValue = channel.unary_unary(
                '/ReplicaService/SaveValue',
                request_serializer=nexusrag__pb2.ValueUpdate.SerializeToString,
                response_deserializer=nexusrag__pb2.SaveAck.FromString,
                _registered_method=True)
        self.SyncUpdate = channel.unary_unary(
                '/ReplicaService/SyncUpdate',
                request_serializer=nexusrag__pb2.ValueUpdate.SerializeToString,
                response_deserializer=nexusrag__pb2.SaveAck.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/ReplicaService/GetValue',
                request_serializer=nexusrag__pb2.ValueQuery.SerializeToString,
                response_deserializer=nexusrag__pb2.ValueState.FromString,
                _registered_method=True)


class ReplicaServiceServicer:
    """============================================================
    Experiment 7: Eventual Consistency via Gossip Replication
    ============================================================

    """

    def SaveValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveValue,
                    request_deserializer=nexusrag__pb2.ValueUpdate.FromString,
                    response_serializer=nexusrag__pb2.SaveAck.SerializeToString,
            ),
            'SyncUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUpdate,
                    request_deserializer=nexusrag__pb2.ValueUpdate.FromString,
                    response_serializer=nexusrag__pb2.SaveAck.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=nexusrag__pb2.ValueQuery.FromString,
                    response_serializer=nexusrag__pb2.ValueState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService:
    """============================================================
    Experiment 7: Eventual Consistency via Gossip Replication
    ============================================================

    """

    @staticmethod
    def SaveValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaService/SaveValue',
            nexusrag__pb2.ValueUpdate.SerializeToString,
            nexusrag__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaService/SyncUpdate',
            nexusrag__pb2.ValueUpdate.SerializeToString,
            nexusrag__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaService/GetValue',
            nexusrag__pb2.ValueQuery.SerializeToString,
            nexusrag__pb2.ValueState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
